CREATE DATABASE FIGURINES;
\c FIGURINES;

/*
CREATE TABLE CATEGORIES (
  nom VARCHAR(42),
  PRIMARY KEY (nom)
);
*/

CREATE TABLE FIGURINE (
  nom VARCHAR(42),
  description VARCHAR(42),
  votespositifs VARCHAR(42),
  votesnegatifs VARCHAR(42),
  nom_1 VARCHAR(42),
  pseudo VARCHAR(42),
  PRIMARY KEY (nom)
);

CREATE TABLE UTILISATEUR (
  pseudo VARCHAR(42),
  email VARCHAR(42),
  PRIMARY KEY (pseudo)
);

CREATE TABLE IMAGE (
  contenu VARCHAR(42),
  nom VARCHAR(42),
  PRIMARY KEY (contenu)
);

CREATE TABLE COMMENTAIRES (
  contenu VARCHAR(42),
  nom VARCHAR(42),
  pseudo VARCHAR(42),
  PRIMARY KEY (contenu)
);

ALTER TABLE FIGURINE ADD FOREIGN KEY (pseudo) REFERENCES UTILISATEUR (pseudo);
-- ALTER TABLE FIGURINE ADD FOREIGN KEY (nom_1) REFERENCES CATEGORIES (nom);
ALTER TABLE IMAGE ADD FOREIGN KEY (nom) REFERENCES FIGURINE (nom);
ALTER TABLE COMMENTAIRES ADD FOREIGN KEY (pseudo) REFERENCES UTILISATEUR (pseudo);
ALTER TABLE COMMENTAIRES ADD FOREIGN KEY (nom) REFERENCES FIGURINE (nom);