BEGIN;

DROP TABLE IF EXISTS "category","users","picture","figurine","comment";

CREATE TABLE IF NOT EXISTS "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "password" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" TEXT NOT NULL UNIQUE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "figurine" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL ,
  "nb_upvote" INT NOT NULL DEFAULT 0,
  "nb_downvote" INT NOT NULL DEFAULT 0,
  "user_id" INT NOT NULL REFERENCES "users"("id"),
  "category_id" INT NOT NULL REFERENCES "category"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "comment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" TEXT NOT NULL,
  "user_id" INT NOT NULL REFERENCES "users"("id"),
  "figurine_id" INT NOT NULL REFERENCES "figurine"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "picture" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "picture_url" TEXT NOT NULL UNIQUE,
  "figurine_id" INT NOT NULL REFERENCES "figurine"("id"),
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ
);

/*SEEDING */
INSERT INTO "users" ("name","email" ,"password") VALUES ('Tatayoyo','emaildetest@test.fr','1234');
INSERT INTO "users" ("name","email" ,"password") VALUES ('Slaan','emaildetruc@test.com','mdptest');

INSERT INTO "category" ("content") VALUES ('Age of Sigmar');
INSERT INTO "category" ("content") VALUES ('Warhammer 40k');

INSERT INTO "figurine" ("name","description","user_id","category_id")
VALUES('Skink Caméleon' , 'Ma première figurine' , 1 , 1);

INSERT INTO "figurine" ("name","description","user_id","category_id")
VALUES('Décor Elfique' , 'Mon super décor' , 1 , 1);

INSERT INTO "figurine" ("name","description","user_id","category_id")
VALUES('Caradryan' , 'Héros Elfe' , 1 , 1);

INSERT INTO "picture" ("picture_url","figurine_id")
VALUES('assets\img\Yk9nLYdw4WMifMTP.jpg' , 1);

INSERT INTO "picture" ("picture_url","figurine_id")
VALUES('https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F667588344745357489%2F&psig=AOvVaw27HwPTeTv0wMKO8yOdu_eR&ust=1619709283047000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPCDu7adofACFQAAAAAdAAAAABAD' , 2);

INSERT INTO "picture" ("picture_url","figurine_id")
VALUES('assets\img\shrine-luminor-lumineth-realm-lords.jpg' , 3);

COMMIT;